// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEDRzYuy57UTZrN0NQle1X7z1zUZuLjgU',
    appId: '1:491987706023:web:fd1b75007752aba7453b82',
    messagingSenderId: '491987706023',
    projectId: 'ptschemistrydata',
    authDomain: 'ptschemistrydata.firebaseapp.com',
    storageBucket: 'ptschemistrydata.firebasestorage.app',
    measurementId: 'G-D7T7J3NCNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsQoY5fJW48UDgyYICLpoYFz26CVRNQAY',
    appId: '1:491987706023:android:7e6f0015eca09e6f453b82',
    messagingSenderId: '491987706023',
    projectId: 'ptschemistrydata',
    storageBucket: 'ptschemistrydata.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcPO8vPgxtV1kIPLBm2k5ynjaQNWCfoeE',
    appId: '1:491987706023:ios:ff3c5309c5bb00b0453b82',
    messagingSenderId: '491987706023',
    projectId: 'ptschemistrydata',
    storageBucket: 'ptschemistrydata.firebasestorage.app',
    iosBundleId: 'com.ptschemistryclass.ptschemistryclass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcPO8vPgxtV1kIPLBm2k5ynjaQNWCfoeE',
    appId: '1:491987706023:ios:ff3c5309c5bb00b0453b82',
    messagingSenderId: '491987706023',
    projectId: 'ptschemistrydata',
    storageBucket: 'ptschemistrydata.firebasestorage.app',
    iosBundleId: 'com.ptschemistryclass.ptschemistryclass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEDRzYuy57UTZrN0NQle1X7z1zUZuLjgU',
    appId: '1:491987706023:web:94470c7df2ace21f453b82',
    messagingSenderId: '491987706023',
    projectId: 'ptschemistrydata',
    authDomain: 'ptschemistrydata.firebaseapp.com',
    storageBucket: 'ptschemistrydata.firebasestorage.app',
    measurementId: 'G-P11J24E3H8',
  );
}
